import type { Product } from "./products";

/**
 * Каталог продавца FYRIA на Kaspi.kz (merchant 18408238).
 * Данные выгружены с Kaspi 13.08.2026: названия, цены, характеристики,
 * рейтинги и артикулы — как на витрине продавца.
 * Файл сгенерирован; правки лучше вносить пересборкой, а не руками.
 */
export const kaspiProducts: Product[] = [
  {
    slug: "fyria-one-chernyi-159430642",
    title: "Мышь FYRIA One черный",
    price: 4990,
    rating: 4.9,
    reviews: 161,
    category: "Мышки",
    sku: "716787619",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/fyria-one-chernyi-159430642/",
    images: [
      "/products/159430642-1.jpg",
      "/products/159430642-2.jpg",
      "/products/159430642-3.jpg",
      "/products/159430642-4.jpg",
    ],
    description:
      "FYRIA One — беспроводная мышь Dual Mode FYRIA One — лёгкая и стильная беспроводная мышь с двойным подключением, идеально подходит для работы, учёбы.",
    specs: [
      { label: "Цвет", value: "черный" },
      { label: "Радиус действия беспроводной мыши", value: "5" },
      { label: "Размер", value: "11.5x6x3.5 см" },
      { label: "Вес", value: "65 г" },
      { label: "Тип подключения", value: "беспроводная" },
      { label: "Тип сенсора", value: "оптическая светодиодная" },
      { label: "Интерфейс", value: "USB, Bluetooth" },
      { label: "Дизайн", value: "для правой руки" },
      { label: "Прокрутка", value: "колесико" },
      { label: "Вертикальная мышь", value: "нет" },
      { label: "Игровая", value: "нет" },
      { label: "Игровой набор", value: "нет" },
      { label: "Разрешение оптического сенсора", value: "1600 dpi" },
      { label: "Количество клавиш", value: "6" },
      { label: "Время отклика", value: "4 мс" },
      { label: "Подсветка", value: "отсутствует" },
      { label: "Источник питания", value: "собственный Li-Ion" },
      { label: "Время работы", value: "180 ч" },
    ],
    highlights: [
      "Цвет: черный",
      "Размер: 11.5x6x3.5 см",
      "Вес: 65 г",
      "Тип подключения: беспроводная",
    ],
  },
  {
    slug: "kabel-fyria-usb-typec-m-lightning-m-1-m-belyi-134326367",
    title: "Кабель FYRIA USB TypeC (M), Lightning (M), 1 м, белый",
    price: 4690,
    rating: 4.9,
    reviews: 543,
    category: "Кабели",
    sku: "286420695",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/kabel-fyria-usb-typec-m-lightning-m-1-m-belyi-134326367/",
    images: [
      "/products/134326367-1.jpg",
      "/products/134326367-2.jpg",
      "/products/134326367-3.jpg",
      "/products/134326367-4.jpg",
    ],
    description:
      "FYRIA подойдет для быстрой подзарядки как iPhone, так и iPad. Он поддерживает технологию Power Delivery. Кабель изготовлен из прочного материала с усилением из оплетки, который защищает внутреннюю проводку от повреждений и износа!",
    specs: [
      { label: "Тип", value: "кабель" },
      { label: "Разъемы", value: "USB TypeC (M), Lightning (M)" },
      { label: "Длина", value: "1 м" },
      {
        label: "Особенности",
        value: "защита от перегрева, тканевая оплетка, функция быстрой зарядки",
      },
      { label: "Цвет", value: "белый" },
    ],
    highlights: [
      "Тип: кабель",
      "Разъемы: USB TypeC (M), Lightning (M)",
      "Длина: 1 м",
      "Цвет: белый",
    ],
  },
  {
    slug: "fyria-one-belyi-159430575",
    title: "Мышь FYRIA One белый",
    price: 4990,
    rating: 4.9,
    reviews: 124,
    category: "Мышки",
    sku: "911463047",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/fyria-one-belyi-159430575/",
    images: [
      "/products/159430575-1.jpg",
      "/products/159430575-2.jpg",
      "/products/159430575-3.jpg",
      "/products/159430575-4.jpg",
    ],
    description:
      "FYRIA One — беспроводная мышь Dual Mode FYRIA One — лёгкая и стильная беспроводная мышь с двойным подключением, идеально подходит для работы, учёбы.",
    specs: [
      { label: "Цвет", value: "белый" },
      { label: "Радиус действия беспроводной мыши", value: "5" },
      { label: "Размер", value: "11.5x6x3.5 см" },
      { label: "Вес", value: "65 г" },
      { label: "Тип подключения", value: "беспроводная" },
      { label: "Тип сенсора", value: "оптическая светодиодная" },
      { label: "Интерфейс", value: "USB, Bluetooth" },
      { label: "Дизайн", value: "для правой руки" },
      { label: "Прокрутка", value: "колесико" },
      { label: "Вертикальная мышь", value: "нет" },
      { label: "Игровая", value: "нет" },
      { label: "Игровой набор", value: "нет" },
      { label: "Разрешение оптического сенсора", value: "1600 dpi" },
      { label: "Количество клавиш", value: "6" },
      { label: "Время отклика", value: "4 мс" },
      { label: "Подсветка", value: "отсутствует" },
      { label: "Время работы", value: "180 ч" },
    ],
    highlights: [
      "Цвет: белый",
      "Размер: 11.5x6x3.5 см",
      "Вес: 65 г",
      "Тип подключения: беспроводная",
    ],
  },
  {
    slug: "fyria-one-rozovyi-159430618",
    title: "Мышь FYRIA One розовый",
    price: 4990,
    rating: 4.9,
    reviews: 109,
    category: "Мышки",
    sku: "411344500",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/fyria-one-rozovyi-159430618/",
    images: [
      "/products/159430618-1.jpg",
      "/products/159430618-2.jpg",
      "/products/159430618-3.jpg",
      "/products/159430618-4.jpg",
    ],
    description:
      "FYRIA One — беспроводная мышь Dual Mode FYRIA One — лёгкая и стильная беспроводная мышь с двойным подключением, идеально подходит для работы, учёбы.",
    specs: [
      { label: "Цвет", value: "розовый" },
      { label: "Радиус действия беспроводной мыши", value: "5" },
      { label: "Размер", value: "11.5x6x3.5 см" },
      { label: "Вес", value: "65 г" },
      { label: "Тип подключения", value: "беспроводная" },
      { label: "Тип сенсора", value: "оптическая светодиодная" },
      { label: "Интерфейс", value: "USB, Bluetooth" },
      { label: "Дизайн", value: "для правой руки" },
      { label: "Прокрутка", value: "колесико" },
      { label: "Вертикальная мышь", value: "нет" },
      { label: "Игровая", value: "нет" },
      { label: "Игровой набор", value: "нет" },
      { label: "Разрешение оптического сенсора", value: "1600 dpi" },
      { label: "Количество клавиш", value: "6" },
      { label: "Время отклика", value: "4 мс" },
      { label: "Подсветка", value: "отсутствует" },
      { label: "Источник питания", value: "собственный Li-Ion" },
      { label: "Время работы", value: "180 ч" },
    ],
    highlights: [
      "Цвет: розовый",
      "Размер: 11.5x6x3.5 см",
      "Вес: 65 г",
      "Тип подключения: беспроводная",
    ],
  },
  {
    slug: "kabel-fyria-usb-typec-m-1-2-m-chernyi-131650945",
    title: "Кабель FYRIA USB TypeC (M), 1.2 м, черный",
    price: 4990,
    rating: 5,
    reviews: 125,
    category: "Кабели",
    sku: "671512641",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/kabel-fyria-usb-typec-m-1-2-m-chernyi-131650945/",
    images: [
      "/products/131650945-1.jpg",
      "/products/131650945-2.jpg",
      "/products/131650945-3.jpg",
      "/products/131650945-4.jpg",
    ],
    description:
      "Кабель быстрой зарядки USB-C. Поддерживает быструю зарядку PD. сплава и нейлоновая оплетка. длина 1.2м Кабель FYRIA S3 USB-C to-C to USB-C aluminum alloy имеет прочную и эластичную нейлоновую оплетку. Благодаря USB Type-C разъемам кабель имеет широкую совместимость со смартфонами, планшетами, с легкостью…",
    specs: [
      { label: "Тип", value: "кабель" },
      { label: "Разъемы", value: "USB TypeC (M)" },
      { label: "Длина", value: "1.2 м" },
      {
        label: "Особенности",
        value: "защита от перегрева, тканевая оплетка, функция быстрой зарядки",
      },
      { label: "Цвет", value: "черный" },
    ],
    highlights: ["Тип: кабель", "Разъемы: USB TypeC (M)", "Длина: 1.2 м", "Цвет: черный"],
  },
  {
    slug: "ofisnoe-kreslo-fyria-prime-pro-seryi-166378738",
    title: "Офисное кресло FYRIA PRIME PRO, серый",
    price: 98990,
    rating: 5,
    reviews: 40,
    category: "Игровые кресла",
    sku: "424597883",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/ofisnoe-kreslo-fyria-prime-pro-seryi-166378738/",
    images: [
      "/products/166378738-1.jpg",
      "/products/166378738-2.jpg",
      "/products/166378738-3.jpg",
      "/products/166378738-4.jpg",
    ],
    description:
      "Офисное кресло FYRIA PRIME PRO, серый. назначение — офисное кресло, материал обивки — сетка, максимальная нагрузка — 150 кг, размеры (вxшxг) — 114 - 133x68x70 см.",
    specs: [
      { label: "Назначение", value: "офисное кресло" },
      { label: "Тип базы", value: "крестовина с колесами" },
      { label: "Материал обивки", value: "сетка" },
      { label: "Тип колес", value: "полумягкие" },
      {
        label: "Регулировка",
        value:
          "высота сиденья, угол наклона, глубина сиденья, жесткость качания, глубина положения подлокотников, высота поясничного упора, подлокотников, высоты подголовника",
      },
      { label: "Максимальная нагрузка", value: "150 кг" },
      { label: "Рекомендуемый рост", value: "до 200" },
      { label: "Максимальный угол наклона спинки", value: "135 град." },
      { label: "Ортопедическое", value: "да" },
      {
        label: "Особенности",
        value:
          "подголовник, подлокотники, механизм качания, спинка из сетки, фиксация спинки в вертикальном положении, фиксация спинки в нескольких положениях, газлифт, антивандальный материал, ортопедическая спинка",
      },
      { label: "Высота сиденья", value: "48-68" },
      { label: "Размеры (ВxШxГ)", value: "114 - 133x68x70 см" },
      {
        label: "Дополнительная информация",
        value:
          "Кресло поставляется в разобранном виде. В комплект входят инструкция и все необходимые принадлежности для самостоятельной сборки.",
      },
      { label: "Цвет", value: "серый" },
      { label: "Тон", value: "однотонный" },
      { label: "Страна", value: "Китай" },
    ],
    highlights: [
      "Назначение: офисное кресло",
      "Тип базы: крестовина с колесами",
      "Материал обивки: сетка",
      "Тип колес: полумягкие",
    ],
  },
  {
    slug: "mikrofon-fyria-yu8-chernyi-152394990",
    title: "Микрофон FYRIA YU8 черный",
    price: 16990,
    rating: 5,
    reviews: 60,
    category: "Микрофоны",
    sku: "038268098",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/mikrofon-fyria-yu8-chernyi-152394990/",
    images: [
      "/products/152394990-1.jpg",
      "/products/152394990-2.jpg",
      "/products/152394990-3.jpg",
      "/products/152394990-4.jpg",
    ],
    description:
      "Микрофон FYRIA YU8 (USB / Type-C) FYRIA YU8 — универсальный конденсаторный микрофон для игр, стриминга, записи голоса, подкастов и онлайн-общения. Оснащён интегрированной технологией шумоподавления, которая эффективно снижает окружающие звуки и делает голос чётким и разборчивым даже в шумной обстановке.",
    specs: [
      { label: "Разъемы", value: "XLR, USB Type-C, mini jack" },
      { label: "Особенности", value: "ветрозащита" },
      { label: "Длина кабеля", value: "2 м" },
      {
        label: "Дополнительная информация",
        value:
          "USB микрофон для игр, стриминга, подкастов и онлайн-общения с шумоподавлением. Plug & Play, совместим с Windows и macOS. Ойын, стриминг және дауыс жазуға арналған USB микрофон. Шу басу технологиясы, Plug & Play, Windows және macOS үйлесімді.",
      },
      { label: "Тип", value: "динамический" },
      { label: "Конструкция", value: "настольный" },
      { label: "Назначение", value: "для компьютера, для блога и стриминга" },
      { label: "Тип подключения", value: "проводной" },
      { label: "Радиосистема", value: "нет" },
      { label: "Цвет", value: "черный" },
    ],
    highlights: [
      "Разъемы: XLR, USB Type-C, mini jack",
      "Особенности: ветрозащита",
      "Длина кабеля: 2 м",
      "Тип: динамический",
    ],
  },
  {
    slug: "mikrofon-fyria-yu8-belyi-152668365",
    title: "Микрофон FYRIA YU8 белый",
    price: 16990,
    rating: 5,
    reviews: 74,
    category: "Микрофоны",
    sku: "932103628",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/mikrofon-fyria-yu8-belyi-152668365/",
    images: [
      "/products/152668365-1.jpg",
      "/products/152668365-2.jpg",
      "/products/152668365-3.jpg",
      "/products/152668365-4.jpg",
    ],
    description:
      "Микрофон FYRIA YU8 (USB / Type-C) FYRIA YU8 — универсальный конденсаторный микрофон для игр, стриминга, записи голоса, подкастов и онлайн-общения. Оснащён интегрированной технологией шумоподавления, которая эффективно снижает окружающие звуки и делает голос чётким и разборчивым даже в шумной обстановке.",
    specs: [
      { label: "Разъемы", value: "XLR, USB Type-C, mini jack" },
      { label: "Особенности", value: "ветрозащита" },
      { label: "Длина кабеля", value: "2 м" },
      {
        label: "Дополнительная информация",
        value:
          "USB микрофон для игр, стриминга, подкастов и онлайн-общения с шумоподавлением. Plug & Play, совместим с Windows и macOS. Ойын, стриминг және дауыс жазуға арналған USB микрофон. Шу басу технологиясы, Plug & Play, Windows және macOS үйлесімді",
      },
      { label: "Тип", value: "динамический" },
      { label: "Конструкция", value: "настольный" },
      { label: "Назначение", value: "для компьютера, для блога и стриминга" },
      { label: "Тип подключения", value: "проводной" },
      { label: "Радиосистема", value: "нет" },
      { label: "Цвет", value: "белый" },
    ],
    highlights: [
      "Разъемы: XLR, USB Type-C, mini jack",
      "Особенности: ветрозащита",
      "Длина кабеля: 2 м",
      "Тип: динамический",
    ],
  },
  {
    slug: "ofisnoe-kreslo-fyria-prime-pro-chernyi-serebrjanyi-166378733",
    title: "Офисное кресло FYRIA PRIME PRO, черный, серебряный",
    price: 98990,
    rating: 5,
    reviews: 23,
    category: "Игровые кресла",
    sku: "543295883",
    inStock: true,
    kaspiUrl:
      "https://kaspi.kz/shop/p/ofisnoe-kreslo-fyria-prime-pro-chernyi-serebrjanyi-166378733/",
    images: [
      "/products/166378733-1.jpg",
      "/products/166378733-2.jpg",
      "/products/166378733-3.jpg",
      "/products/166378733-4.jpg",
    ],
    description:
      "Офисное кресло FYRIA PRIME PRO, черный, серебряный. назначение — офисное кресло, материал обивки — сетка, максимальная нагрузка — 150 кг, размеры (вxшxг) — 114 - 133х68x70 см.",
    specs: [
      { label: "Назначение", value: "офисное кресло" },
      { label: "Тип базы", value: "крестовина с колесами" },
      { label: "Материал обивки", value: "сетка" },
      { label: "Тип колес", value: "полумягкие" },
      {
        label: "Регулировка",
        value:
          "высота сиденья, угол наклона, глубина сиденья, жесткость качания, глубина положения подлокотников, высота поясничного упора, подлокотников, высоты подголовника",
      },
      { label: "Максимальная нагрузка", value: "150 кг" },
      { label: "Рекомендуемый рост", value: "до 200 см" },
      { label: "Максимальный угол наклона спинки", value: "135 град." },
      { label: "Ортопедическое", value: "да" },
      {
        label: "Особенности",
        value:
          "подголовник, подлокотники, механизм качания, спинка из сетки, фиксация спинки в вертикальном положении, фиксация спинки в нескольких положениях, газлифт, антивандальный материал, ортопедическая спинка",
      },
      { label: "Высота сиденья", value: "48-68" },
      { label: "Размеры (ВxШxГ)", value: "114 - 133х68x70 см" },
      {
        label: "Дополнительная информация",
        value:
          "Кресло поставляется в разобранном виде. В комплект входят инструкция и все необходимые принадлежности для самостоятельной сборки.",
      },
      { label: "Цвет", value: "черный, серебряный" },
      { label: "Тон", value: "однотонный" },
      { label: "Страна", value: "Китай" },
    ],
    highlights: [
      "Назначение: офисное кресло",
      "Тип базы: крестовина с колесами",
      "Материал обивки: сетка",
      "Тип колес: полумягкие",
    ],
  },
  {
    slug: "fyria-f7-15-6-8-gb-ssd-256-gb-win-11-pro-f7-166356019",
    title: 'Ноутбук FYRIA F7 15.6" / 8 Гб / SSD 256 Гб / Win 11 Pro / F7',
    price: 199990,
    rating: 5,
    reviews: 25,
    category: "Ноутбуки",
    sku: "737360536",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/fyria-f7-15-6-8-gb-ssd-256-gb-win-11-pro-f7-166356019/",
    images: [
      "/products/166356019-1.jpg",
      "/products/166356019-2.jpg",
      "/products/166356019-3.jpg",
      "/products/166356019-4.jpg",
    ],
    description:
      "FYRIA F7 — надёжный и производительный ноутбук с большим экраном для работы, учёбы и повседневных задач Нужен мощный ноутбук с большим экраном и стильным дизайном? FYRIA F7 — это сбалансированное решение с процессором Intel, большим объёмом памяти и качественным дисплеем.",
    specs: [
      { label: "Тип", value: "для работы и учебы, ультрабук" },
      { label: "Операционная система", value: "Win 11 Pro" },
      {
        label: "Версия операционной системы",
        value:
          "Предустановленная Windows, не активированная (Гарантийные обязательства на программное обеспечение не распространяются)",
      },
      { label: "Диагональ экрана", value: "15.6 дюйм" },
      { label: "Разрешение экрана", value: "1920x1080" },
      { label: "Частота обновления экрана", value: "60 Гц" },
      { label: "Покрытие экрана", value: "матовое" },
      { label: "Тип матрицы", value: "IPS" },
      { label: "Максимальная частота процессора", value: "2900 МГц" },
      { label: "Модель процессора", value: "Intel Celeron N5095" },
      { label: "Базовая частота процессора", value: "2000 МГц" },
      { label: "Количество ядер процессора", value: "4 ядра" },
      { label: "Размер оперативной памяти", value: "8 Гб" },
      { label: "Тип жесткого диска", value: "SSD" },
      { label: "Общий объем накопителей", value: "256 Гб" },
      { label: "Тип видеоадаптера", value: "встроенная видеокарта" },
      { label: "Видеокарта", value: "Intel UHD Graphics" },
      { label: "Стандарт Wi-Fi", value: "802.11ac/a/b/g/n" },
      { label: "Количество интерфейсов USB 3.0", value: "2" },
      { label: "Входы", value: "наушники" },
      { label: "Выходы", value: "mini HDMI" },
      { label: "Подсветка клавиатуры", value: "да" },
      { label: "Раскладка клавиатуры", value: "русская, английская" },
      { label: "Цвет", value: "серый" },
      { label: "Сканер отпечатка пальца", value: "да" },
      { label: "Вес", value: "1.7 кг" },
    ],
    highlights: [
      "Тип: для работы и учебы, ультрабук",
      "Операционная система: Win 11 Pro",
      "Диагональ экрана: 15.6 дюйм",
      "Разрешение экрана: 1920x1080",
    ],
  },
  {
    slug: "kabel-fyria-usb-typec-m-1-m-s1-belyi-142640865",
    title: "Кабель FYRIA USB TypeC (M), 1 м, S1 белый",
    price: 4990,
    rating: 4.9,
    reviews: 82,
    category: "Кабели",
    sku: "18182388",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/kabel-fyria-usb-typec-m-1-m-s1-belyi-142640865/",
    images: [
      "/products/142640865-1.jpg",
      "/products/142640865-2.jpg",
      "/products/142640865-3.jpg",
      "/products/142640865-4.jpg",
    ],
    description:
      "Кабель FYRIA USB TypeC (M), 1 м — надежное решение для быстрой зарядки и передачи данных, обеспечивающее долговечность и безопасность использования. Особенности: - Защита от короткого замыкания — предотвращает повреждение устройств. - Тканевая оплетка — обеспечивает дополнительную прочность и защиту.",
    specs: [
      { label: "Тип", value: "кабель" },
      { label: "Разъемы", value: "USB TypeC (M)" },
      { label: "Длина", value: "1 м" },
      {
        label: "Особенности",
        value: "защита от перегрева, тканевая оплетка, функция быстрой зарядки",
      },
      { label: "Цвет", value: "белый" },
    ],
    highlights: ["Тип: кабель", "Разъемы: USB TypeC (M)", "Длина: 1 м", "Цвет: белый"],
  },
  {
    slug: "fyria-pd-30-usb-type-c-lightning-belyi-142751245",
    title: "Зарядное устройство FYRIA PD 30 USB Type-C, Lightning белый",
    price: 3990,
    rating: 4.9,
    reviews: 57,
    category: "Зарядки",
    sku: "326715721",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/fyria-pd-30-usb-type-c-lightning-belyi-142751245/",
    images: [
      "/products/142751245-1.jpg",
      "/products/142751245-2.jpg",
      "/products/142751245-3.jpg",
      "/products/142751245-4.jpg",
    ],
    description:
      "Зарядное устройство FYRIA PD 30 USB Type-C, Lightning белый. тип — сетевая зарядка, мощность зарядки — 30 Вт, стандарт быстрой зарядки — Power Delivery, Quick Charge 3.0, разъем подключения — Lightning, USB Type-C.",
    specs: [
      { label: "Тип", value: "сетевая зарядка" },
      { label: "Количество подключаемых устройств", value: "1" },
      { label: "Максимальный выходной ток", value: "3 А" },
      { label: "Напряжение", value: "220 В" },
      { label: "Быстрая зарядка", value: "да" },
      { label: "Стандарт быстрой зарядки", value: "Power Delivery, Quick Charge 3.0" },
      { label: "Разъем подключения", value: "Lightning, USB Type-C" },
      { label: "Совместимость", value: "APPLE, Samsung, Xiaomi, Huawei, Poco" },
      { label: "Особенности", value: "защита от перегрева" },
      { label: "Мощность зарядки", value: "30 Вт" },
      { label: "Цвет", value: "белый" },
    ],
    highlights: [
      "Тип: сетевая зарядка",
      "Максимальный выходной ток: 3 А",
      "Напряжение: 220 В",
      "Быстрая зарядка: да",
    ],
  },
  {
    slug: "fyria-car-p63-usb-type-c-usb-chernyi-142759260",
    title: "Зарядное устройство FYRIA CAR P63 USB Type-C, USB черный",
    price: 4590,
    rating: 4.9,
    reviews: 71,
    category: "Зарядки",
    sku: "935016096",
    inStock: true,
    kaspiUrl: "https://kaspi.kz/shop/p/fyria-car-p63-usb-type-c-usb-chernyi-142759260/",
    images: [
      "/products/142759260-1.jpg",
      "/products/142759260-2.jpg",
      "/products/142759260-3.jpg",
      "/products/142759260-4.jpg",
    ],
    description:
      "Автомобильное зарядное устройство FYRIA CAR P63 — эффективное решение для быстрой зарядки ваших устройств в дороге. С мощностью 75 Вт и поддержкой быстрой зарядки вы сможете зарядить два устройства одновременно, не теряя времени. Особенности: - Защита от перегрева — обеспечивает безопасность во время зарядки.",
    specs: [
      { label: "Тип", value: "автомобильная зарядка" },
      { label: "Количество подключаемых устройств", value: "2" },
      { label: "Максимальный выходной ток", value: "3 А" },
      { label: "Напряжение", value: "12 В" },
      { label: "Быстрая зарядка", value: "да" },
      { label: "Стандарт быстрой зарядки", value: "Power Delivery, Quick Charge 3.0" },
      { label: "Разъем подключения", value: "USB Type-C, USB" },
      { label: "Совместимость", value: "Универсальный" },
      { label: "Особенности", value: "защита от перегрева" },
      { label: "Мощность зарядки", value: "75 Вт" },
      { label: "Цвет", value: "черный" },
    ],
    highlights: [
      "Тип: автомобильная зарядка",
      "Максимальный выходной ток: 3 А",
      "Напряжение: 12 В",
      "Быстрая зарядка: да",
    ],
  },
];
